### ISSUE TITLE
好项目，有没有打算继续丰富下组件

### ISSUE THREAD

**Issue by m01i0ng** [vrx-arco/arco-design-pro#1]
加入以下组件 
- ProTable
- ProSelect
......

**Comment by Colourlessglow** [comment]
短期内可能没有相关想法

虽然这个项目依赖的灵感源自 `ant-design` 的 `pro-components` 

但一开始做这个项目的源动力还是为了满足类似 [ruoyi](https://ruoyi.vip/) 这种简单中后台的项目的快速搭建

近期最大的更新其实也是围绕着官方实现的 `<ColorPicker/>`中
- 由于官方实现和这边相差过大，为了防止重复轮子，`1.5.0` 时删除了当时基于ant-design 样式的颜色选择器组件
- 后续由于官方实现一直存在问题，并持续一个月未修复, 基于 [@vrx/color-picker-kit](https://vrx-vue.github.io/color-picker-kit/) 实现了一版可选的 `@vrx-arco/color-picker`

实现的组件已满足自身需求的情况下， 本项目短时间内组件的数量将处于一个停滞阶段了...

**如果您有一些想自己实现的组件，欢迎您 fork 本项目**
